# 基础镜像使用java
FROM java:8u111-jdk
# 作者
#MAINTAINER zxy rubble@qq.com
# VOLUME 指定了临时文件目录为/tmp。
# 其效果是在主机 /var/lib/docker 目录下创建了一个临时文件，并链接到容器的/tmp
VOLUME /tmp
# 将jar包添加到容器中并更名为app.jar
ADD sway-camp-0.0.1-SNAPSHOT.jar app.jar
# 运行jar包 前面的add命令把jar复制过去，后面touch命令的作用是修改这个文件的访问时间和修改时间为当前时间。
RUN bash -c 'touch /app.jar'
# 指定加密算法urandom
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]